AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'go-syllabus'

Parameters:
  DomainName:
    Type: String

  HostedZoneId:
    Type: String

Globals:
  Function:
    Runtime: go1.x
    Handler: main
    Timeout: 10

Resources:
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.syllabus.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "api.syllabus.${DomainName}"
          HostedZoneId: !Ref HostedZoneId

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app/lambda/hello-world
      Events:
        API:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

Outputs:
  HelloWorldAPI:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
